/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.netbeans.modules.php.analysis.ui.options;

import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.event.ChangeListener;
import javax.swing.event.DocumentListener;
import org.netbeans.modules.php.analysis.commands.Psalm;
import org.netbeans.modules.php.analysis.options.AnalysisOptions;
import org.netbeans.modules.php.analysis.options.AnalysisOptionsValidator;
import org.netbeans.modules.php.analysis.ui.AnalysisDefaultDocumentListener;
import org.netbeans.modules.php.analysis.ui.PsalmLevelListCellRenderer;
import org.netbeans.modules.php.analysis.options.ValidatorPsalmParameter;
import org.netbeans.modules.php.analysis.util.AnalysisUiUtils;
import org.netbeans.modules.php.api.validation.ValidationResult;
import org.openide.awt.HtmlBrowser;
import org.openide.awt.Mnemonics;
import org.openide.util.ChangeSupport;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;

public class PsalmOptionsPanel extends AnalysisCategoryPanel {

    private static final long serialVersionUID = 1199550925948622972L;

    private final ChangeSupport changeSupport = new ChangeSupport(this);

    /**
     * Creates new form PsalmOptionsPanel
     */
    public PsalmOptionsPanel() {
        super();
        initComponents();
        init();
    }

    @NbBundle.Messages({
        "# {0} - short script name",
        "# {1} - long script name",
        "PsalmOptionsPanel.hint=Full path of Psalm script (typically {0} or {1}).",})
    private void init() {
        psalmHintLabel.setText(Bundle.PsalmOptionsPanel_hint(Psalm.NAME, Psalm.LONG_NAME));
        psalmLevelComboBox.removeAllItems();
        // NETBEANS-2974
        // allow empty level option to use a level of a configuration file
        psalmLevelComboBox.addItem(""); // NOI18N
        for (int i = AnalysisOptions.PHPSTAN_MIN_LEVEL; i <= AnalysisOptions.PHPSTAN_MAX_LEVEL; i++) {
            psalmLevelComboBox.addItem(String.valueOf(i));
        }
        psalmLevelComboBox.addItem(Psalm.MAX_LEVEL);
        psalmLevelComboBox.setRenderer(new PsalmLevelListCellRenderer(psalmLevelComboBox.getRenderer()));
        // add listener
        DocumentListener defaultDocumentListener = new AnalysisDefaultDocumentListener(() -> fireChange());
        psalmTextField.getDocument().addDocumentListener(defaultDocumentListener);
        psalmConfigurationTextField.getDocument().addDocumentListener(defaultDocumentListener);
        psalmMemoryLimitTextField.getDocument().addDocumentListener(defaultDocumentListener);
        psalmLevelComboBox.addActionListener(e -> fireChange());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        psalmLabel = new javax.swing.JLabel();
        psalmTextField = new javax.swing.JTextField();
        psalmBrowseButton = new javax.swing.JButton();
        psalmSearchButton = new javax.swing.JButton();
        psalmHintLabel = new javax.swing.JLabel();
        psalmLevelLabel = new javax.swing.JLabel();
        psalmLevelComboBox = new javax.swing.JComboBox<String>();
        psalmMemoryLimitLabel = new javax.swing.JLabel();
        psalmMemoryLimitTextField = new javax.swing.JTextField();
        psalmConfigurationLabel = new javax.swing.JLabel();
        psalmConfigurationTextField = new javax.swing.JTextField();
        psalmConfigurationInfoLabel = new javax.swing.JLabel();
        psalmConfiturationBrowseButton = new javax.swing.JButton();
        psalmNoteLabel = new javax.swing.JLabel();
        psalmMinVersionInfoLabel = new javax.swing.JLabel();
        psalmLearnMoreLabel = new javax.swing.JLabel();

        psalmLabel.setLabelFor(psalmTextField);
        org.openide.awt.Mnemonics.setLocalizedText(psalmLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(psalmBrowseButton, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmBrowseButton.text")); // NOI18N
        psalmBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psalmBrowseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(psalmSearchButton, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmSearchButton.text")); // NOI18N
        psalmSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psalmSearchButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(psalmHintLabel, "HINT"); // NOI18N

        psalmLevelLabel.setLabelFor(psalmLevelComboBox);
        org.openide.awt.Mnemonics.setLocalizedText(psalmLevelLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmLevelLabel.text")); // NOI18N

        psalmLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7" }));

        psalmMemoryLimitLabel.setLabelFor(psalmMemoryLimitTextField);
        org.openide.awt.Mnemonics.setLocalizedText(psalmMemoryLimitLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmMemoryLimitLabel.text")); // NOI18N

        psalmConfigurationLabel.setLabelFor(psalmConfigurationTextField);
        org.openide.awt.Mnemonics.setLocalizedText(psalmConfigurationLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmConfigurationLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(psalmConfigurationInfoLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmConfigurationInfoLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(psalmConfiturationBrowseButton, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmConfiturationBrowseButton.text")); // NOI18N
        psalmConfiturationBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psalmConfiturationBrowseButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(psalmNoteLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmNoteLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(psalmMinVersionInfoLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmMinVersionInfoLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(psalmLearnMoreLabel, org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmLearnMoreLabel.text")); // NOI18N
        psalmLearnMoreLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psalmLearnMoreLabelMousePressed(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                psalmLearnMoreLabelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psalmMinVersionInfoLabel)
                    .addComponent(psalmLearnMoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(psalmConfigurationLabel)
                    .addComponent(psalmLabel)
                    .addComponent(psalmLevelLabel)
                    .addComponent(psalmNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psalmMemoryLimitLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(psalmConfigurationInfoLabel)
                            .addComponent(psalmLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(psalmMemoryLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 66, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(psalmConfigurationTextField)
                            .addComponent(psalmTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(psalmHintLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(psalmBrowseButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(psalmSearchButton))
                            .addComponent(psalmConfiturationBrowseButton)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psalmLabel)
                    .addComponent(psalmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psalmBrowseButton)
                    .addComponent(psalmSearchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psalmHintLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psalmConfigurationLabel)
                    .addComponent(psalmConfigurationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psalmConfiturationBrowseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psalmConfigurationInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psalmLevelLabel)
                    .addComponent(psalmLevelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(psalmMemoryLimitLabel)
                    .addComponent(psalmMemoryLimitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(psalmNoteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psalmMinVersionInfoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psalmLearnMoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        psalmLabel.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(PsalmOptionsPanel.class, "PsalmOptionsPanel.psalmLabel.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void psalmBrowseButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_psalmBrowseButtonActionPerformed
        File file = AnalysisUiUtils.browsePsalm();
        if (file != null) {
            psalmTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_psalmBrowseButtonActionPerformed

    private void psalmSearchButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_psalmSearchButtonActionPerformed
        String psalm = AnalysisUiUtils.searchPsalm();
        if (psalm != null) {
            psalmTextField.setText(psalm);
        }
    }//GEN-LAST:event_psalmSearchButtonActionPerformed

    private void psalmLearnMoreLabelMouseEntered(MouseEvent evt) {//GEN-FIRST:event_psalmLearnMoreLabelMouseEntered
        evt.getComponent().setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_psalmLearnMoreLabelMouseEntered

    private void psalmLearnMoreLabelMousePressed(MouseEvent evt) {//GEN-FIRST:event_psalmLearnMoreLabelMousePressed
        try {
            URL url = new URL("https://github.com/vimeo/psalm"); // NOI18N
            HtmlBrowser.URLDisplayer.getDefault().showURL(url);
        } catch (MalformedURLException ex) {
            Exceptions.printStackTrace(ex);
        }
    }//GEN-LAST:event_psalmLearnMoreLabelMousePressed

    private void psalmConfiturationBrowseButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_psalmConfiturationBrowseButtonActionPerformed
        File file = AnalysisUiUtils.browsePsalmConfiguration();
        if (file != null) {
            psalmConfigurationTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_psalmConfiturationBrowseButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton psalmBrowseButton;
    private javax.swing.JLabel psalmConfigurationInfoLabel;
    private javax.swing.JLabel psalmConfigurationLabel;
    private javax.swing.JTextField psalmConfigurationTextField;
    private javax.swing.JButton psalmConfiturationBrowseButton;
    private javax.swing.JLabel psalmHintLabel;
    private javax.swing.JLabel psalmLabel;
    private javax.swing.JLabel psalmLearnMoreLabel;
    private javax.swing.JComboBox<String> psalmLevelComboBox;
    private javax.swing.JLabel psalmLevelLabel;
    private javax.swing.JLabel psalmMemoryLimitLabel;
    private javax.swing.JTextField psalmMemoryLimitTextField;
    private javax.swing.JLabel psalmMinVersionInfoLabel;
    private javax.swing.JLabel psalmNoteLabel;
    private javax.swing.JButton psalmSearchButton;
    private javax.swing.JTextField psalmTextField;
    // End of variables declaration//GEN-END:variables

    @NbBundle.Messages("PsalmOptionsPanel.category.name=Psalm")
    @Override
    public String getCategoryName() {
        return Bundle.PsalmOptionsPanel_category_name();
    }

    @Override
    public void addChangeListener(ChangeListener listener) {
        changeSupport.addChangeListener(listener);
    }

    @Override
    public void removeChangeListener(ChangeListener listener) {
        changeSupport.removeChangeListener(listener);
    }

    @Override
    public void update() {
        AnalysisOptions options = AnalysisOptions.getInstance();
        setPsalmPath(options.getPsalmPath());
        setPsalmConfigurationPath(options.getPsalmConfigurationPath());
        setPsalmLevel(options.getPsalmLevel());
        setPsalmMemoryLimit(options.getPsalmMemoryLimit());
    }

    @Override
    public void applyChanges() {
        AnalysisOptions options = AnalysisOptions.getInstance();
        options.setPsalmPath(getPsalmPath());
        options.setPsalmConfigurationPath(getPsalmConfigurationPath());
        options.setPsalmLevel(getPsalmLevel());
        options.setPsalmMemoryLimit(getPsalmMemoryLimit());
    }

    @Override
    public boolean isChanged() {
        String saved = AnalysisOptions.getInstance().getPsalmPath();
        String current = getPsalmPath();
        if (saved == null ? !current.isEmpty() : !saved.equals(current)) {
            return true;
        }
        saved = AnalysisOptions.getInstance().getPsalmConfigurationPath();
        current = getPsalmConfigurationPath();
        if (saved == null ? !current.isEmpty() : !saved.equals(current)) {
            return true;
        }
        String savedString = AnalysisOptions.getInstance().getPsalmLevel();
        String currentString = getPsalmLevel();
        return !savedString.equals(currentString);
    }

    @Override
    public ValidationResult getValidationResult() {
        return new AnalysisOptionsValidator()
                .validatePsalm(ValidatorPsalmParameter.create(this))
                .getResult();
    }

    void fireChange() {
        changeSupport.fireChange();
    }

    public String getPsalmPath() {
        return psalmTextField.getText().trim();
    }

    private void setPsalmPath(String path) {
        psalmTextField.setText(path);
    }

    public String getPsalmConfigurationPath() {
        return psalmConfigurationTextField.getText().trim();
    }

    private void setPsalmConfigurationPath(String path) {
        psalmConfigurationTextField.setText(path);
    }

    public String getPsalmLevel() {
        return (String) psalmLevelComboBox.getSelectedItem();
    }

    private void setPsalmLevel(String level) {
        psalmLevelComboBox.setSelectedItem(level);
    }

    public String getPsalmMemoryLimit() {
        return psalmMemoryLimitTextField.getText().trim();
    }

    private void setPsalmMemoryLimit(String memoryLimit) {
        psalmMemoryLimitTextField.setText(memoryLimit);
    }
}
